var N = null;var sourcesIndex = {};
sourcesIndex["aplusb"] = {"name":"","files":["aplusb.rs"]};
sourcesIndex["bipartitematching"] = {"name":"","files":["bipartitematching.rs"]};
sourcesIndex["competitive_library"] = {"name":"","dirs":[{"name":"algebra","files":["base.rs","mod.rs","operations.rs"]},{"name":"algorithm","files":["compress.rs","convex_hull_trick.rs","mod.rs","search.rs","slide_minimum.rs"]},{"name":"data_structure","files":["binary_indexed_tree.rs","bitset.rs","disjoint_sparse_table.rs","mod.rs","segment_tree.rs","sliding_winsow_aggregation.rs","union_find.rs"]},{"name":"geometry","files":["circle.rs","closest_pair.rs","complex.rs","line.rs","mod.rs","polygon.rs"]},{"name":"graph","files":["base.rs","maximum_flow.rs","minimum_cost_flow.rs","mod.rs","strongly_connected_component.rs","topological_sort.rs"]},{"name":"math","files":["anymod.rs","anymodu32.rs","factorial.rs","gcd.rs","matrix.rs","mod.rs","modi64.rs","modu32.rs","nums.rs","polynomial.rs","prime.rs","quad_double.rs"]},{"name":"string","files":["knuth_morris_pratt.rs","mod.rs","rolling_hash.rs","suffix_array.rs","z_algorithm.rs"]},{"name":"tools","files":["input.rs","iterable.rs","mod.rs","output.rs","random.rs"]},{"name":"tree","files":["depth.rs","euler_tour.rs","mod.rs","rerooting.rs","tree.rs"]}],"files":["lib.rs"]};
sourcesIndex["lca"] = {"name":"","files":["lca.rs"]};
sourcesIndex["many_aplusb"] = {"name":"","files":["many_aplusb.rs"]};
sourcesIndex["point_add_range_sum_binary_indexed_tree"] = {"name":"","files":["point_add_range_sum-binary_indexed_tree.rs"]};
sourcesIndex["point_add_range_sum_segment_tree"] = {"name":"","files":["point_add_range_sum-segment_tree.rs"]};
sourcesIndex["point_set_range_composite"] = {"name":"","files":["point_set_range_composite.rs"]};
sourcesIndex["queue_operate_all_composite"] = {"name":"","files":["queue_operate_all_composite.rs"]};
sourcesIndex["range_affine_range_sum"] = {"name":"","files":["range_affine_range_sum.rs"]};
sourcesIndex["scc"] = {"name":"","files":["scc.rs"]};
sourcesIndex["staticrmq_disjoint_sparse_table"] = {"name":"","files":["staticrmq-disjoint_sparse_table.rs"]};
sourcesIndex["staticrmq_segment_tree"] = {"name":"","files":["staticrmq-segment_tree.rs"]};
sourcesIndex["suffixarray"] = {"name":"","files":["suffixarray.rs"]};
sourcesIndex["two_sat"] = {"name":"","files":["two_sat.rs"]};
sourcesIndex["unionfind"] = {"name":"","files":["unionfind.rs"]};
sourcesIndex["zalgorithm"] = {"name":"","files":["zalgorithm.rs"]};
createSourceSidebar();
